version: '3'

services:
  backend:
    container_name: 'nest'
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    restart: always
    ports:
      - 4000:3000
    depends_on:
      - postgres
    networks:
      - nest-postgres

  postgres:
    container_name: 'postgres'
    image: postgres:12.12-alpine
    restart: always
    env_file: ./.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - nest-postgres

  frontend:
    container_name: 'frontend'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:80
    depends_on:
      - backend

volumes:
  pgdata:

networks:
  nest-postgres:
    driver: bridge
