version: '3'

services:
  backend:
    container_name: 'nest'
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: ./.env
    restart: always
    ports:
      - 4000:3000
    depends_on:
      - postgres
    networks:
      - nest-postgres

  postgres:
    container_name: 'postgres'
    image: postgres:14
    restart: always
    env_file: ./.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - nest-postgres

  frontend:
    container_name: 'frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:80

volumes:
  pgdata:

networks:
  nest-postgres:
    driver: bridge
